"""Append one scorecard's headline numbers to `battle/RESULTS.md`, which is tracked
unlike the gitignored scorecards themselves.

    uv run python -m battle.orchestrator.summarize battle/results/<scorecard>.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

SUMMARY_FILE = Path(__file__).resolve().parents[1] / "RESULTS.md"

HEADER = """# Battle run results

Generated by `battle.orchestrator.summarize`, one row per completed run. Both `lost` and
`pending` count a submitted task with no execution recorded; the split is whether anything
could still redeliver it. A drain that completed, or one that timed out against an empty
broker, files them under `lost`; a broker still holding messages, or an early-ack run where
an empty broker proves nothing, files them under `pending`. Rows written before the broker
scan understood the stock transport report a stock drain timeout as `pending` regardless.
Stock-transport and early-ack runs are report-only, never pass/fail.

| finished | transport | pool | profile | submitted | exactly once | lost | pending | failed | dupes h/s/u | kills | p50 | p95 | p99 | max | past VT | event loss | verdict |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
"""


def _row(scorecard: dict[str, Any], stamp: str) -> str:
    config, tasks, latency = scorecard["config"], scorecard["tasks"], scorecard["latency"]
    overall = latency["overall"]
    verdict = scorecard["verdict"]
    worst_event_loss = max((event["loss_pct"] for event in scorecard["events"].values()), default=0.0)
    dupes = "/".join(str(tasks[f"duplicates_{kind}"]) for kind in ("hard_kill", "soft_kill", "unattributed"))
    mark = "PASS" if verdict["passed"] else "FAIL"
    return (
        f"| {stamp} | {config['transport']} | {config.get('pool', 'prefork')} | {config['profile']} "
        f"| {tasks['submitted']} | {tasks['exactly_once']} | **{tasks['lost']}** | {tasks['pending']} "
        f"| {tasks['failed']} | {dupes} | {len(scorecard['kills'])} "
        f"| {overall['p50']:.2f}s | {overall['p95']:.2f}s | {overall['p99']:.2f}s | {overall['max']:.2f}s "
        f"| {latency['first_exec_past_vt']} | {worst_event_loss:.3f}% "
        f"| {mark if verdict['mode'] == 'enforced' else 'report-only'} |\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    path = Path(argv[1])
    scorecard = json.loads(path.read_text())

    if not SUMMARY_FILE.exists():
        SUMMARY_FILE.write_text(HEADER)
    with SUMMARY_FILE.open("a") as handle:
        handle.write(_row(scorecard, path.stem.split("-")[1]))

    failures = scorecard["verdict"]["failures"]
    if failures:
        with SUMMARY_FILE.open("a") as handle:
            handle.write(f"\n<!-- {path.name} failures: {'; '.join(failures)} -->\n")
    print(f"summary updated: {SUMMARY_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
